# Generated by Django 4.0.2 on 2022-02-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('cls', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=10, max_length=10)),
                ('grade', models.CharField(choices=[('1', 'A+'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D')], default='A+', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_exam', models.DateField()),
                ('date_of_issue', models.DateField(auto_now=True)),
                ('character_of_student', models.CharField(choices=[('1', 'Outstanding'), ('2', 'Very Good'), ('3', 'Good'), ('4', 'Average')], default='good', max_length=50)),
                ('issuer', models.CharField(max_length=255)),
            ],
        ),
    ]
