# Generated by Django 4.0.2 on 2022-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_issue',
            field=models.DateField(),
        ),
    ]
