# Generated by Django 4.0.2 on 2022-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls', models.CharField(max_length=4)),
                ('subject_code', models.CharField(max_length=10)),
                ('subjects', models.CharField(max_length=255)),
                ('credit_hour', models.FloatField(max_length=10)),
                ('grade_point', models.FloatField(max_length=10)),
                ('grade', models.CharField(max_length=5)),
                ('final_grade', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=40)),
            ],
        ),
    ]
