# Generated by Django 3.2.3 on 2022-02-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cls',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='final_grade',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D')], default='A+', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'A'), ('3', 'B+'), ('4', 'B'), ('5', 'C+'), ('6', 'C'), ('7', 'D+'), ('8', 'D')], default='A+', max_length=10),
        ),
    ]
