# Generated by Django 4.0.2 on 2022-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20220220_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_gpa',
            field=models.CharField(default='3.5', max_length=10),
        ),
    ]
